// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: H5ExtTransferResponse.proto

#ifndef PROTOBUF_H5ExtTransferResponse_2eproto__INCLUDED
#define PROTOBUF_H5ExtTransferResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BaseResponse.pb.h"
#include "JsApiResponse.pb.h"
// @@protoc_insertion_point(includes)
namespace MMPro {
namespace micromsg {
class BaseResponse;
class BaseResponseDefaultTypeInternal;
extern BaseResponseDefaultTypeInternal _BaseResponse_default_instance_;
class H5ExtTransferResponse;
class H5ExtTransferResponseDefaultTypeInternal;
extern H5ExtTransferResponseDefaultTypeInternal _H5ExtTransferResponse_default_instance_;
class JsApiResponse;
class JsApiResponseDefaultTypeInternal;
extern JsApiResponseDefaultTypeInternal _JsApiResponse_default_instance_;
}  // namespace micromsg
}  // namespace MMPro

namespace MMPro {
namespace micromsg {

namespace protobuf_H5ExtTransferResponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_H5ExtTransferResponse_2eproto

// ===================================================================

class H5ExtTransferResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MMPro.micromsg.H5ExtTransferResponse) */ {
 public:
  H5ExtTransferResponse();
  virtual ~H5ExtTransferResponse();

  H5ExtTransferResponse(const H5ExtTransferResponse& from);

  inline H5ExtTransferResponse& operator=(const H5ExtTransferResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const H5ExtTransferResponse& default_instance();

  static inline const H5ExtTransferResponse* internal_default_instance() {
    return reinterpret_cast<const H5ExtTransferResponse*>(
               &_H5ExtTransferResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(H5ExtTransferResponse* other);

  // implements Message ----------------------------------------------

  inline H5ExtTransferResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  H5ExtTransferResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const H5ExtTransferResponse& from);
  void MergeFrom(const H5ExtTransferResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(H5ExtTransferResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
  bool has__baseresponse() const;
  void clear__baseresponse();
  static const int kBaseResponseFieldNumber = 1;
  const ::MMPro::micromsg::BaseResponse& _baseresponse() const;
  ::MMPro::micromsg::BaseResponse* mutable__baseresponse();
  ::MMPro::micromsg::BaseResponse* release__baseresponse();
  void set_allocated__baseresponse(::MMPro::micromsg::BaseResponse* _baseresponse);

  // optional .MMPro.micromsg.JsApiResponse _jsApiResponse = 2;
  bool has__jsapiresponse() const;
  void clear__jsapiresponse();
  static const int kJsApiResponseFieldNumber = 2;
  const ::MMPro::micromsg::JsApiResponse& _jsapiresponse() const;
  ::MMPro::micromsg::JsApiResponse* mutable__jsapiresponse();
  ::MMPro::micromsg::JsApiResponse* release__jsapiresponse();
  void set_allocated__jsapiresponse(::MMPro::micromsg::JsApiResponse* _jsapiresponse);

  // @@protoc_insertion_point(class_scope:MMPro.micromsg.H5ExtTransferResponse)
 private:
  void set_has__baseresponse();
  void clear_has__baseresponse();
  void set_has__jsapiresponse();
  void clear_has__jsapiresponse();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::MMPro::micromsg::BaseResponse* _baseresponse_;
  ::MMPro::micromsg::JsApiResponse* _jsapiresponse_;
  friend struct protobuf_H5ExtTransferResponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// H5ExtTransferResponse

// required .MMPro.micromsg.BaseResponse _BaseResponse = 1;
inline bool H5ExtTransferResponse::has__baseresponse() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void H5ExtTransferResponse::set_has__baseresponse() {
  _has_bits_[0] |= 0x00000001u;
}
inline void H5ExtTransferResponse::clear_has__baseresponse() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void H5ExtTransferResponse::clear__baseresponse() {
  if (_baseresponse_ != NULL) _baseresponse_->::MMPro::micromsg::BaseResponse::Clear();
  clear_has__baseresponse();
}
inline const ::MMPro::micromsg::BaseResponse& H5ExtTransferResponse::_baseresponse() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.H5ExtTransferResponse._BaseResponse)
  return _baseresponse_ != NULL ? *_baseresponse_
                         : *::MMPro::micromsg::BaseResponse::internal_default_instance();
}
inline ::MMPro::micromsg::BaseResponse* H5ExtTransferResponse::mutable__baseresponse() {
  set_has__baseresponse();
  if (_baseresponse_ == NULL) {
    _baseresponse_ = new ::MMPro::micromsg::BaseResponse;
  }
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.H5ExtTransferResponse._BaseResponse)
  return _baseresponse_;
}
inline ::MMPro::micromsg::BaseResponse* H5ExtTransferResponse::release__baseresponse() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.H5ExtTransferResponse._BaseResponse)
  clear_has__baseresponse();
  ::MMPro::micromsg::BaseResponse* temp = _baseresponse_;
  _baseresponse_ = NULL;
  return temp;
}
inline void H5ExtTransferResponse::set_allocated__baseresponse(::MMPro::micromsg::BaseResponse* _baseresponse) {
  delete _baseresponse_;
  _baseresponse_ = _baseresponse;
  if (_baseresponse) {
    set_has__baseresponse();
  } else {
    clear_has__baseresponse();
  }
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.H5ExtTransferResponse._BaseResponse)
}

// optional .MMPro.micromsg.JsApiResponse _jsApiResponse = 2;
inline bool H5ExtTransferResponse::has__jsapiresponse() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void H5ExtTransferResponse::set_has__jsapiresponse() {
  _has_bits_[0] |= 0x00000002u;
}
inline void H5ExtTransferResponse::clear_has__jsapiresponse() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void H5ExtTransferResponse::clear__jsapiresponse() {
  if (_jsapiresponse_ != NULL) _jsapiresponse_->::MMPro::micromsg::JsApiResponse::Clear();
  clear_has__jsapiresponse();
}
inline const ::MMPro::micromsg::JsApiResponse& H5ExtTransferResponse::_jsapiresponse() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.H5ExtTransferResponse._jsApiResponse)
  return _jsapiresponse_ != NULL ? *_jsapiresponse_
                         : *::MMPro::micromsg::JsApiResponse::internal_default_instance();
}
inline ::MMPro::micromsg::JsApiResponse* H5ExtTransferResponse::mutable__jsapiresponse() {
  set_has__jsapiresponse();
  if (_jsapiresponse_ == NULL) {
    _jsapiresponse_ = new ::MMPro::micromsg::JsApiResponse;
  }
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.H5ExtTransferResponse._jsApiResponse)
  return _jsapiresponse_;
}
inline ::MMPro::micromsg::JsApiResponse* H5ExtTransferResponse::release__jsapiresponse() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.H5ExtTransferResponse._jsApiResponse)
  clear_has__jsapiresponse();
  ::MMPro::micromsg::JsApiResponse* temp = _jsapiresponse_;
  _jsapiresponse_ = NULL;
  return temp;
}
inline void H5ExtTransferResponse::set_allocated__jsapiresponse(::MMPro::micromsg::JsApiResponse* _jsapiresponse) {
  delete _jsapiresponse_;
  _jsapiresponse_ = _jsapiresponse;
  if (_jsapiresponse) {
    set_has__jsapiresponse();
  } else {
    clear_has__jsapiresponse();
  }
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.H5ExtTransferResponse._jsApiResponse)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_H5ExtTransferResponse_2eproto__INCLUDED
