// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JsApiResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "JsApiResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MMPro {
namespace micromsg {
class JsApiResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<JsApiResponse> {
} _JsApiResponse_default_instance_;

namespace protobuf_JsApiResponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiResponse, _ret_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiResponse, _errormsg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiResponse, _respjson_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(JsApiResponse, _header_),
  2,
  0,
  1,
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 9, sizeof(JsApiResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_JsApiResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "JsApiResponse.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _JsApiResponse_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::MMPro::micromsg::protobuf_TransferJsApiHeader_2eproto::InitDefaults();
  _JsApiResponse_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023JsApiResponse.proto\022\016MMPro.micromsg\032\031T"
      "ransferJsApiHeader.proto\"y\n\rJsApiRespons"
      "e\022\014\n\004_Ret\030\001 \001(\005\022\021\n\t_ErrorMsg\030\002 \001(\t\022\021\n\t_R"
      "espJson\030\003 \001(\t\0224\n\007_Header\030\004 \003(\0132#.MMPro.m"
      "icromsg.TransferJsApiHeader"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "JsApiResponse.proto", &protobuf_RegisterTypes);
  ::MMPro::micromsg::protobuf_TransferJsApiHeader_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_JsApiResponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JsApiResponse::kRetFieldNumber;
const int JsApiResponse::kErrorMsgFieldNumber;
const int JsApiResponse::kRespJsonFieldNumber;
const int JsApiResponse::kHeaderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JsApiResponse::JsApiResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_JsApiResponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MMPro.micromsg.JsApiResponse)
}
JsApiResponse::JsApiResponse(const JsApiResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      _header_(from._header_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _errormsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has__errormsg()) {
    _errormsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._errormsg_);
  }
  _respjson_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has__respjson()) {
    _respjson_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._respjson_);
  }
  _ret_ = from._ret_;
  // @@protoc_insertion_point(copy_constructor:MMPro.micromsg.JsApiResponse)
}

void JsApiResponse::SharedCtor() {
  _cached_size_ = 0;
  _errormsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _respjson_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _ret_ = 0;
}

JsApiResponse::~JsApiResponse() {
  // @@protoc_insertion_point(destructor:MMPro.micromsg.JsApiResponse)
  SharedDtor();
}

void JsApiResponse::SharedDtor() {
  _errormsg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _respjson_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void JsApiResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* JsApiResponse::descriptor() {
  protobuf_JsApiResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_JsApiResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const JsApiResponse& JsApiResponse::default_instance() {
  protobuf_JsApiResponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

JsApiResponse* JsApiResponse::New(::google::protobuf::Arena* arena) const {
  JsApiResponse* n = new JsApiResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void JsApiResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MMPro.micromsg.JsApiResponse)
  _header_.Clear();
  if (_has_bits_[0 / 32] & 3u) {
    if (has__errormsg()) {
      GOOGLE_DCHECK(!_errormsg_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*_errormsg_.UnsafeRawStringPointer())->clear();
    }
    if (has__respjson()) {
      GOOGLE_DCHECK(!_respjson_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*_respjson_.UnsafeRawStringPointer())->clear();
    }
  }
  _ret_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool JsApiResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MMPro.micromsg.JsApiResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 _Ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has__ret();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string _ErrorMsg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__errormsg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->_errormsg().data(), this->_errormsg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MMPro.micromsg.JsApiResponse._ErrorMsg");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string _RespJson = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__respjson()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->_respjson().data(), this->_respjson().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MMPro.micromsg.JsApiResponse._RespJson");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add__header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MMPro.micromsg.JsApiResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MMPro.micromsg.JsApiResponse)
  return false;
#undef DO_
}

void JsApiResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MMPro.micromsg.JsApiResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 _Ret = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->_ret(), output);
  }

  // optional string _ErrorMsg = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_errormsg().data(), this->_errormsg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiResponse._ErrorMsg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->_errormsg(), output);
  }

  // optional string _RespJson = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_respjson().data(), this->_respjson().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiResponse._RespJson");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->_respjson(), output);
  }

  // repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
  for (unsigned int i = 0, n = this->_header_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_header(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MMPro.micromsg.JsApiResponse)
}

::google::protobuf::uint8* JsApiResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MMPro.micromsg.JsApiResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 _Ret = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->_ret(), target);
  }

  // optional string _ErrorMsg = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_errormsg().data(), this->_errormsg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiResponse._ErrorMsg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->_errormsg(), target);
  }

  // optional string _RespJson = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_respjson().data(), this->_respjson().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.JsApiResponse._RespJson");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->_respjson(), target);
  }

  // repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
  for (unsigned int i = 0, n = this->_header_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->_header(i), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MMPro.micromsg.JsApiResponse)
  return target;
}

size_t JsApiResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MMPro.micromsg.JsApiResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
  {
    unsigned int count = this->_header_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->_header(i));
    }
  }

  if (_has_bits_[0 / 32] & 7u) {
    // optional string _ErrorMsg = 2;
    if (has__errormsg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->_errormsg());
    }

    // optional string _RespJson = 3;
    if (has__respjson()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->_respjson());
    }

    // optional int32 _Ret = 1;
    if (has__ret()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->_ret());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void JsApiResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MMPro.micromsg.JsApiResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const JsApiResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const JsApiResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MMPro.micromsg.JsApiResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MMPro.micromsg.JsApiResponse)
    MergeFrom(*source);
  }
}

void JsApiResponse::MergeFrom(const JsApiResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MMPro.micromsg.JsApiResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  _header_.MergeFrom(from._header_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has__errormsg();
      _errormsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._errormsg_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has__respjson();
      _respjson_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._respjson_);
    }
    if (cached_has_bits & 0x00000004u) {
      _ret_ = from._ret_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void JsApiResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MMPro.micromsg.JsApiResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JsApiResponse::CopyFrom(const JsApiResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MMPro.micromsg.JsApiResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JsApiResponse::IsInitialized() const {
  return true;
}

void JsApiResponse::Swap(JsApiResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JsApiResponse::InternalSwap(JsApiResponse* other) {
  _header_.InternalSwap(&other->_header_);
  _errormsg_.Swap(&other->_errormsg_);
  _respjson_.Swap(&other->_respjson_);
  std::swap(_ret_, other->_ret_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata JsApiResponse::GetMetadata() const {
  protobuf_JsApiResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_JsApiResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// JsApiResponse

// optional int32 _Ret = 1;
bool JsApiResponse::has__ret() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void JsApiResponse::set_has__ret() {
  _has_bits_[0] |= 0x00000004u;
}
void JsApiResponse::clear_has__ret() {
  _has_bits_[0] &= ~0x00000004u;
}
void JsApiResponse::clear__ret() {
  _ret_ = 0;
  clear_has__ret();
}
::google::protobuf::int32 JsApiResponse::_ret() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._Ret)
  return _ret_;
}
void JsApiResponse::set__ret(::google::protobuf::int32 value) {
  set_has__ret();
  _ret_ = value;
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiResponse._Ret)
}

// optional string _ErrorMsg = 2;
bool JsApiResponse::has__errormsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void JsApiResponse::set_has__errormsg() {
  _has_bits_[0] |= 0x00000001u;
}
void JsApiResponse::clear_has__errormsg() {
  _has_bits_[0] &= ~0x00000001u;
}
void JsApiResponse::clear__errormsg() {
  _errormsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__errormsg();
}
const ::std::string& JsApiResponse::_errormsg() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._ErrorMsg)
  return _errormsg_.GetNoArena();
}
void JsApiResponse::set__errormsg(const ::std::string& value) {
  set_has__errormsg();
  _errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
#if LANG_CXX11
void JsApiResponse::set__errormsg(::std::string&& value) {
  set_has__errormsg();
  _errormsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
#endif
void JsApiResponse::set__errormsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__errormsg();
  _errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
void JsApiResponse::set__errormsg(const char* value, size_t size) {
  set_has__errormsg();
  _errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
::std::string* JsApiResponse::mutable__errormsg() {
  set_has__errormsg();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiResponse._ErrorMsg)
  return _errormsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JsApiResponse::release__errormsg() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiResponse._ErrorMsg)
  clear_has__errormsg();
  return _errormsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JsApiResponse::set_allocated__errormsg(::std::string* _errormsg) {
  if (_errormsg != NULL) {
    set_has__errormsg();
  } else {
    clear_has__errormsg();
  }
  _errormsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _errormsg);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiResponse._ErrorMsg)
}

// optional string _RespJson = 3;
bool JsApiResponse::has__respjson() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void JsApiResponse::set_has__respjson() {
  _has_bits_[0] |= 0x00000002u;
}
void JsApiResponse::clear_has__respjson() {
  _has_bits_[0] &= ~0x00000002u;
}
void JsApiResponse::clear__respjson() {
  _respjson_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__respjson();
}
const ::std::string& JsApiResponse::_respjson() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._RespJson)
  return _respjson_.GetNoArena();
}
void JsApiResponse::set__respjson(const ::std::string& value) {
  set_has__respjson();
  _respjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiResponse._RespJson)
}
#if LANG_CXX11
void JsApiResponse::set__respjson(::std::string&& value) {
  set_has__respjson();
  _respjson_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiResponse._RespJson)
}
#endif
void JsApiResponse::set__respjson(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__respjson();
  _respjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiResponse._RespJson)
}
void JsApiResponse::set__respjson(const char* value, size_t size) {
  set_has__respjson();
  _respjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiResponse._RespJson)
}
::std::string* JsApiResponse::mutable__respjson() {
  set_has__respjson();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiResponse._RespJson)
  return _respjson_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* JsApiResponse::release__respjson() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiResponse._RespJson)
  clear_has__respjson();
  return _respjson_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void JsApiResponse::set_allocated__respjson(::std::string* _respjson) {
  if (_respjson != NULL) {
    set_has__respjson();
  } else {
    clear_has__respjson();
  }
  _respjson_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _respjson);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiResponse._RespJson)
}

// repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
int JsApiResponse::_header_size() const {
  return _header_.size();
}
void JsApiResponse::clear__header() {
  _header_.Clear();
}
const ::MMPro::micromsg::TransferJsApiHeader& JsApiResponse::_header(int index) const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._Header)
  return _header_.Get(index);
}
::MMPro::micromsg::TransferJsApiHeader* JsApiResponse::mutable__header(int index) {
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiResponse._Header)
  return _header_.Mutable(index);
}
::MMPro::micromsg::TransferJsApiHeader* JsApiResponse::add__header() {
  // @@protoc_insertion_point(field_add:MMPro.micromsg.JsApiResponse._Header)
  return _header_.Add();
}
::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader >*
JsApiResponse::mutable__header() {
  // @@protoc_insertion_point(field_mutable_list:MMPro.micromsg.JsApiResponse._Header)
  return &_header_;
}
const ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader >&
JsApiResponse::_header() const {
  // @@protoc_insertion_point(field_list:MMPro.micromsg.JsApiResponse._Header)
  return _header_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)
