// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JsApiResponse.proto

#ifndef PROTOBUF_JsApiResponse_2eproto__INCLUDED
#define PROTOBUF_JsApiResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "TransferJsApiHeader.pb.h"
// @@protoc_insertion_point(includes)
namespace MMPro {
namespace micromsg {
class JsApiResponse;
class JsApiResponseDefaultTypeInternal;
extern JsApiResponseDefaultTypeInternal _JsApiResponse_default_instance_;
class TransferJsApiHeader;
class TransferJsApiHeaderDefaultTypeInternal;
extern TransferJsApiHeaderDefaultTypeInternal _TransferJsApiHeader_default_instance_;
}  // namespace micromsg
}  // namespace MMPro

namespace MMPro {
namespace micromsg {

namespace protobuf_JsApiResponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_JsApiResponse_2eproto

// ===================================================================

class JsApiResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MMPro.micromsg.JsApiResponse) */ {
 public:
  JsApiResponse();
  virtual ~JsApiResponse();

  JsApiResponse(const JsApiResponse& from);

  inline JsApiResponse& operator=(const JsApiResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JsApiResponse& default_instance();

  static inline const JsApiResponse* internal_default_instance() {
    return reinterpret_cast<const JsApiResponse*>(
               &_JsApiResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(JsApiResponse* other);

  // implements Message ----------------------------------------------

  inline JsApiResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  JsApiResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JsApiResponse& from);
  void MergeFrom(const JsApiResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JsApiResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
  int _header_size() const;
  void clear__header();
  static const int kHeaderFieldNumber = 4;
  const ::MMPro::micromsg::TransferJsApiHeader& _header(int index) const;
  ::MMPro::micromsg::TransferJsApiHeader* mutable__header(int index);
  ::MMPro::micromsg::TransferJsApiHeader* add__header();
  ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader >*
      mutable__header();
  const ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader >&
      _header() const;

  // optional string _ErrorMsg = 2;
  bool has__errormsg() const;
  void clear__errormsg();
  static const int kErrorMsgFieldNumber = 2;
  const ::std::string& _errormsg() const;
  void set__errormsg(const ::std::string& value);
  #if LANG_CXX11
  void set__errormsg(::std::string&& value);
  #endif
  void set__errormsg(const char* value);
  void set__errormsg(const char* value, size_t size);
  ::std::string* mutable__errormsg();
  ::std::string* release__errormsg();
  void set_allocated__errormsg(::std::string* _errormsg);

  // optional string _RespJson = 3;
  bool has__respjson() const;
  void clear__respjson();
  static const int kRespJsonFieldNumber = 3;
  const ::std::string& _respjson() const;
  void set__respjson(const ::std::string& value);
  #if LANG_CXX11
  void set__respjson(::std::string&& value);
  #endif
  void set__respjson(const char* value);
  void set__respjson(const char* value, size_t size);
  ::std::string* mutable__respjson();
  ::std::string* release__respjson();
  void set_allocated__respjson(::std::string* _respjson);

  // optional int32 _Ret = 1;
  bool has__ret() const;
  void clear__ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::int32 _ret() const;
  void set__ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MMPro.micromsg.JsApiResponse)
 private:
  void set_has__ret();
  void clear_has__ret();
  void set_has__errormsg();
  void clear_has__errormsg();
  void set_has__respjson();
  void clear_has__respjson();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader > _header_;
  ::google::protobuf::internal::ArenaStringPtr _errormsg_;
  ::google::protobuf::internal::ArenaStringPtr _respjson_;
  ::google::protobuf::int32 _ret_;
  friend struct protobuf_JsApiResponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// JsApiResponse

// optional int32 _Ret = 1;
inline bool JsApiResponse::has__ret() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JsApiResponse::set_has__ret() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JsApiResponse::clear_has__ret() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JsApiResponse::clear__ret() {
  _ret_ = 0;
  clear_has__ret();
}
inline ::google::protobuf::int32 JsApiResponse::_ret() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._Ret)
  return _ret_;
}
inline void JsApiResponse::set__ret(::google::protobuf::int32 value) {
  set_has__ret();
  _ret_ = value;
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiResponse._Ret)
}

// optional string _ErrorMsg = 2;
inline bool JsApiResponse::has__errormsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JsApiResponse::set_has__errormsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JsApiResponse::clear_has__errormsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JsApiResponse::clear__errormsg() {
  _errormsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__errormsg();
}
inline const ::std::string& JsApiResponse::_errormsg() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._ErrorMsg)
  return _errormsg_.GetNoArena();
}
inline void JsApiResponse::set__errormsg(const ::std::string& value) {
  set_has__errormsg();
  _errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
#if LANG_CXX11
inline void JsApiResponse::set__errormsg(::std::string&& value) {
  set_has__errormsg();
  _errormsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
#endif
inline void JsApiResponse::set__errormsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__errormsg();
  _errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
inline void JsApiResponse::set__errormsg(const char* value, size_t size) {
  set_has__errormsg();
  _errormsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiResponse._ErrorMsg)
}
inline ::std::string* JsApiResponse::mutable__errormsg() {
  set_has__errormsg();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiResponse._ErrorMsg)
  return _errormsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsApiResponse::release__errormsg() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiResponse._ErrorMsg)
  clear_has__errormsg();
  return _errormsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsApiResponse::set_allocated__errormsg(::std::string* _errormsg) {
  if (_errormsg != NULL) {
    set_has__errormsg();
  } else {
    clear_has__errormsg();
  }
  _errormsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _errormsg);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiResponse._ErrorMsg)
}

// optional string _RespJson = 3;
inline bool JsApiResponse::has__respjson() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JsApiResponse::set_has__respjson() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JsApiResponse::clear_has__respjson() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JsApiResponse::clear__respjson() {
  _respjson_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__respjson();
}
inline const ::std::string& JsApiResponse::_respjson() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._RespJson)
  return _respjson_.GetNoArena();
}
inline void JsApiResponse::set__respjson(const ::std::string& value) {
  set_has__respjson();
  _respjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.JsApiResponse._RespJson)
}
#if LANG_CXX11
inline void JsApiResponse::set__respjson(::std::string&& value) {
  set_has__respjson();
  _respjson_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.JsApiResponse._RespJson)
}
#endif
inline void JsApiResponse::set__respjson(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__respjson();
  _respjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.JsApiResponse._RespJson)
}
inline void JsApiResponse::set__respjson(const char* value, size_t size) {
  set_has__respjson();
  _respjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.JsApiResponse._RespJson)
}
inline ::std::string* JsApiResponse::mutable__respjson() {
  set_has__respjson();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiResponse._RespJson)
  return _respjson_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JsApiResponse::release__respjson() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.JsApiResponse._RespJson)
  clear_has__respjson();
  return _respjson_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JsApiResponse::set_allocated__respjson(::std::string* _respjson) {
  if (_respjson != NULL) {
    set_has__respjson();
  } else {
    clear_has__respjson();
  }
  _respjson_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _respjson);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.JsApiResponse._RespJson)
}

// repeated .MMPro.micromsg.TransferJsApiHeader _Header = 4;
inline int JsApiResponse::_header_size() const {
  return _header_.size();
}
inline void JsApiResponse::clear__header() {
  _header_.Clear();
}
inline const ::MMPro::micromsg::TransferJsApiHeader& JsApiResponse::_header(int index) const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.JsApiResponse._Header)
  return _header_.Get(index);
}
inline ::MMPro::micromsg::TransferJsApiHeader* JsApiResponse::mutable__header(int index) {
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.JsApiResponse._Header)
  return _header_.Mutable(index);
}
inline ::MMPro::micromsg::TransferJsApiHeader* JsApiResponse::add__header() {
  // @@protoc_insertion_point(field_add:MMPro.micromsg.JsApiResponse._Header)
  return _header_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader >*
JsApiResponse::mutable__header() {
  // @@protoc_insertion_point(field_mutable_list:MMPro.micromsg.JsApiResponse._Header)
  return &_header_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MMPro::micromsg::TransferJsApiHeader >&
JsApiResponse::_header() const {
  // @@protoc_insertion_point(field_list:MMPro.micromsg.JsApiResponse._Header)
  return _header_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_JsApiResponse_2eproto__INCLUDED
