// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransferJsApiHeader.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TransferJsApiHeader.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MMPro {
namespace micromsg {
class TransferJsApiHeaderDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TransferJsApiHeader> {
} _TransferJsApiHeader_default_instance_;

namespace protobuf_TransferJsApiHeader_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransferJsApiHeader, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransferJsApiHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransferJsApiHeader, _key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransferJsApiHeader, _value_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(TransferJsApiHeader)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_TransferJsApiHeader_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "TransferJsApiHeader.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _TransferJsApiHeader_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _TransferJsApiHeader_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\031TransferJsApiHeader.proto\022\016MMPro.micro"
      "msg\"3\n\023TransferJsApiHeader\022\014\n\004_Key\030\001 \001(\t"
      "\022\016\n\006_Value\030\002 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 96);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TransferJsApiHeader.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_TransferJsApiHeader_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TransferJsApiHeader::kKeyFieldNumber;
const int TransferJsApiHeader::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TransferJsApiHeader::TransferJsApiHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_TransferJsApiHeader_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MMPro.micromsg.TransferJsApiHeader)
}
TransferJsApiHeader::TransferJsApiHeader(const TransferJsApiHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has__key()) {
    _key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._key_);
  }
  _value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has__value()) {
    _value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._value_);
  }
  // @@protoc_insertion_point(copy_constructor:MMPro.micromsg.TransferJsApiHeader)
}

void TransferJsApiHeader::SharedCtor() {
  _cached_size_ = 0;
  _key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

TransferJsApiHeader::~TransferJsApiHeader() {
  // @@protoc_insertion_point(destructor:MMPro.micromsg.TransferJsApiHeader)
  SharedDtor();
}

void TransferJsApiHeader::SharedDtor() {
  _key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TransferJsApiHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TransferJsApiHeader::descriptor() {
  protobuf_TransferJsApiHeader_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_TransferJsApiHeader_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TransferJsApiHeader& TransferJsApiHeader::default_instance() {
  protobuf_TransferJsApiHeader_2eproto::InitDefaults();
  return *internal_default_instance();
}

TransferJsApiHeader* TransferJsApiHeader::New(::google::protobuf::Arena* arena) const {
  TransferJsApiHeader* n = new TransferJsApiHeader;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TransferJsApiHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:MMPro.micromsg.TransferJsApiHeader)
  if (_has_bits_[0 / 32] & 3u) {
    if (has__key()) {
      GOOGLE_DCHECK(!_key_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*_key_.UnsafeRawStringPointer())->clear();
    }
    if (has__value()) {
      GOOGLE_DCHECK(!_value_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*_value_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TransferJsApiHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MMPro.micromsg.TransferJsApiHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string _Key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->_key().data(), this->_key().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MMPro.micromsg.TransferJsApiHeader._Key");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string _Value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->_value().data(), this->_value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MMPro.micromsg.TransferJsApiHeader._Value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MMPro.micromsg.TransferJsApiHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MMPro.micromsg.TransferJsApiHeader)
  return false;
#undef DO_
}

void TransferJsApiHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MMPro.micromsg.TransferJsApiHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string _Key = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_key().data(), this->_key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.TransferJsApiHeader._Key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->_key(), output);
  }

  // optional string _Value = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_value().data(), this->_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.TransferJsApiHeader._Value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->_value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MMPro.micromsg.TransferJsApiHeader)
}

::google::protobuf::uint8* TransferJsApiHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MMPro.micromsg.TransferJsApiHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string _Key = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_key().data(), this->_key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.TransferJsApiHeader._Key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->_key(), target);
  }

  // optional string _Value = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_value().data(), this->_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MMPro.micromsg.TransferJsApiHeader._Value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->_value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MMPro.micromsg.TransferJsApiHeader)
  return target;
}

size_t TransferJsApiHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MMPro.micromsg.TransferJsApiHeader)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string _Key = 1;
    if (has__key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->_key());
    }

    // optional string _Value = 2;
    if (has__value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->_value());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TransferJsApiHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MMPro.micromsg.TransferJsApiHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const TransferJsApiHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TransferJsApiHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MMPro.micromsg.TransferJsApiHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MMPro.micromsg.TransferJsApiHeader)
    MergeFrom(*source);
  }
}

void TransferJsApiHeader::MergeFrom(const TransferJsApiHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MMPro.micromsg.TransferJsApiHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has__key();
      _key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._key_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has__value();
      _value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._value_);
    }
  }
}

void TransferJsApiHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MMPro.micromsg.TransferJsApiHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransferJsApiHeader::CopyFrom(const TransferJsApiHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MMPro.micromsg.TransferJsApiHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransferJsApiHeader::IsInitialized() const {
  return true;
}

void TransferJsApiHeader::Swap(TransferJsApiHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TransferJsApiHeader::InternalSwap(TransferJsApiHeader* other) {
  _key_.Swap(&other->_key_);
  _value_.Swap(&other->_value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TransferJsApiHeader::GetMetadata() const {
  protobuf_TransferJsApiHeader_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_TransferJsApiHeader_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TransferJsApiHeader

// optional string _Key = 1;
bool TransferJsApiHeader::has__key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TransferJsApiHeader::set_has__key() {
  _has_bits_[0] |= 0x00000001u;
}
void TransferJsApiHeader::clear_has__key() {
  _has_bits_[0] &= ~0x00000001u;
}
void TransferJsApiHeader::clear__key() {
  _key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__key();
}
const ::std::string& TransferJsApiHeader::_key() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.TransferJsApiHeader._Key)
  return _key_.GetNoArena();
}
void TransferJsApiHeader::set__key(const ::std::string& value) {
  set_has__key();
  _key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.TransferJsApiHeader._Key)
}
#if LANG_CXX11
void TransferJsApiHeader::set__key(::std::string&& value) {
  set_has__key();
  _key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.TransferJsApiHeader._Key)
}
#endif
void TransferJsApiHeader::set__key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__key();
  _key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.TransferJsApiHeader._Key)
}
void TransferJsApiHeader::set__key(const char* value, size_t size) {
  set_has__key();
  _key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.TransferJsApiHeader._Key)
}
::std::string* TransferJsApiHeader::mutable__key() {
  set_has__key();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.TransferJsApiHeader._Key)
  return _key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransferJsApiHeader::release__key() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.TransferJsApiHeader._Key)
  clear_has__key();
  return _key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransferJsApiHeader::set_allocated__key(::std::string* _key) {
  if (_key != NULL) {
    set_has__key();
  } else {
    clear_has__key();
  }
  _key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _key);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.TransferJsApiHeader._Key)
}

// optional string _Value = 2;
bool TransferJsApiHeader::has__value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TransferJsApiHeader::set_has__value() {
  _has_bits_[0] |= 0x00000002u;
}
void TransferJsApiHeader::clear_has__value() {
  _has_bits_[0] &= ~0x00000002u;
}
void TransferJsApiHeader::clear__value() {
  _value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has__value();
}
const ::std::string& TransferJsApiHeader::_value() const {
  // @@protoc_insertion_point(field_get:MMPro.micromsg.TransferJsApiHeader._Value)
  return _value_.GetNoArena();
}
void TransferJsApiHeader::set__value(const ::std::string& value) {
  set_has__value();
  _value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MMPro.micromsg.TransferJsApiHeader._Value)
}
#if LANG_CXX11
void TransferJsApiHeader::set__value(::std::string&& value) {
  set_has__value();
  _value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MMPro.micromsg.TransferJsApiHeader._Value)
}
#endif
void TransferJsApiHeader::set__value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has__value();
  _value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MMPro.micromsg.TransferJsApiHeader._Value)
}
void TransferJsApiHeader::set__value(const char* value, size_t size) {
  set_has__value();
  _value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MMPro.micromsg.TransferJsApiHeader._Value)
}
::std::string* TransferJsApiHeader::mutable__value() {
  set_has__value();
  // @@protoc_insertion_point(field_mutable:MMPro.micromsg.TransferJsApiHeader._Value)
  return _value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransferJsApiHeader::release__value() {
  // @@protoc_insertion_point(field_release:MMPro.micromsg.TransferJsApiHeader._Value)
  clear_has__value();
  return _value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransferJsApiHeader::set_allocated__value(::std::string* _value) {
  if (_value != NULL) {
    set_has__value();
  } else {
    clear_has__value();
  }
  _value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _value);
  // @@protoc_insertion_point(field_set_allocated:MMPro.micromsg.TransferJsApiHeader._Value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace micromsg
}  // namespace MMPro

// @@protoc_insertion_point(global_scope)
